"""v8.0__init_care - MOD-006 care schema storage foundation

PHASE-8 T01 (#417): the storage layer the care case and e-prescription
module builds on. Creates the ``care`` schema with ``care_cases``
(patient, doctor, pre_summary, stage, closed_at, close_reason),
``care_prescriptions`` (status, source, attempt_no, draft_snapshot,
issued_at, attributed_doctor), ``care_rx_items`` (sequence, name, dose,
duration), ``care_rx_approvals`` (doctor_id, decision, edited_yn,
reason, verification_declaration, declared_at, approved_at),
``care_doctor_inputs`` (input_type, media_ref, sensitive_class), and
the module's transactional outbox + consumed-events ledger. All tables
live under the private ``care`` schema with no cross-schema foreign
keys (ADR-0003). Table names follow the namespace prefix rule
(coding-standards S2): every table starts with ``care_``.

Revision ID: 145ca8587d12
Revises: 7a5c02e3d481
Create Date: 2026-09-14 12:00:00.000000
"""

from collections.abc import Sequence

from alembic import op

revision: str = "145ca8587d12"
down_revision: str | Sequence[str] | None = "7a5c02e3d481"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS care")

    # ------------------------------------------------------------------
    # care_cases - the core case record (FEAT-008, FEAT-009)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE care.care_cases (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            patient_id BIGINT NOT NULL,
            doctor_id BIGINT,
            pre_summary_id BIGINT,
            stage VARCHAR(30) NOT NULL DEFAULT 'pre_summary',
            closed_at TIMESTAMPTZ,
            close_reason VARCHAR(50),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_care_cases_stage
                CHECK (stage IN (
                    'pre_summary', 'consult_complete',
                    'prescription_pending', 'closed'
                )),
            CONSTRAINT ck_care_cases_close_reason
                CHECK (close_reason IS NULL OR close_reason IN (
                    'patient_withdrawn', 'doctor_rejected',
                    'no_show', 'duplicate', 'system'
                ))
        )
        """
    )
    op.execute("CREATE INDEX ix_care_cases_patient ON care.care_cases (patient_id, created_at)")
    op.execute("CREATE INDEX ix_care_cases_doctor ON care.care_cases (doctor_id, stage)")

    # ------------------------------------------------------------------
    # care_prescriptions - e-prescription lifecycle (FEAT-009)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE care.care_prescriptions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            case_id BIGINT NOT NULL,
            status VARCHAR(30) NOT NULL DEFAULT 'draft',
            source VARCHAR(20) NOT NULL DEFAULT 'ai_draft',
            attempt_no INT NOT NULL DEFAULT 1,
            draft_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
            issued_at TIMESTAMPTZ,
            attributed_doctor BIGINT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_care_prescriptions_case
                FOREIGN KEY (case_id) REFERENCES care.care_cases (id),
            CONSTRAINT ck_care_prescriptions_status
                CHECK (status IN (
                    'draft', 'doctor_reviewed', 'approved',
                    'rejected', 'issued', 'fulfilled'
                )),
            CONSTRAINT ck_care_prescriptions_source
                CHECK (source IN ('ai_draft', 'manual'))
        )
        """
    )
    op.execute("CREATE INDEX ix_care_prescriptions_case ON care.care_prescriptions (case_id)")

    # ------------------------------------------------------------------
    # care_rx_items - individual medication line items
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE care.care_rx_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prescription_id BIGINT NOT NULL,
            sequence INT NOT NULL DEFAULT 1,
            name VARCHAR(200) NOT NULL,
            dose VARCHAR(100),
            duration VARCHAR(100),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_care_rx_items_prescription
                FOREIGN KEY (prescription_id) REFERENCES care.care_prescriptions (id)
        )
        """
    )
    op.execute("CREATE INDEX ix_care_rx_items_prescription ON care.care_rx_items (prescription_id)")

    # ------------------------------------------------------------------
    # care_rx_approvals - doctor approval/rejection audit (REQ-023)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE care.care_rx_approvals (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prescription_id BIGINT NOT NULL,
            doctor_id BIGINT NOT NULL,
            decision VARCHAR(20) NOT NULL,
            edited_yn BOOLEAN NOT NULL DEFAULT false,
            reason TEXT,
            verification_declaration TEXT,
            declared_at TIMESTAMPTZ,
            approved_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_care_rx_approvals_prescription
                FOREIGN KEY (prescription_id) REFERENCES care.care_prescriptions (id),
            CONSTRAINT ck_care_rx_approvals_decision
                CHECK (decision IN ('approved', 'rejected'))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_care_rx_approvals_prescription ON care.care_rx_approvals (prescription_id)"
    )

    # ------------------------------------------------------------------
    # care_doctor_inputs - voice/photo doctor inputs
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE care.care_doctor_inputs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            case_id BIGINT NOT NULL,
            input_type VARCHAR(10) NOT NULL,
            media_ref TEXT NOT NULL,
            sensitive_class VARCHAR(30),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_care_doctor_inputs_case
                FOREIGN KEY (case_id) REFERENCES care.care_cases (id),
            CONSTRAINT ck_care_doctor_inputs_input_type
                CHECK (input_type IN ('voice', 'photo')),
            CONSTRAINT ck_care_doctor_inputs_sensitive_class
                CHECK (sensitive_class IS NULL OR sensitive_class IN (
                    'normal', 'sensitive', 'restricted'
                ))
        )
        """
    )
    op.execute("CREATE INDEX ix_care_doctor_inputs_case ON care.care_doctor_inputs (case_id)")

    # ------------------------------------------------------------------
    # care_outbox - transactional outbox (ADR-0002)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE care.care_outbox (
            id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
            event_id UUID NOT NULL,
            event_type VARCHAR(100) NOT NULL,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            occurred_at TIMESTAMPTZ NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            attempts INT NOT NULL DEFAULT 0,
            next_attempt_at TIMESTAMPTZ,
            CONSTRAINT ck_care_outbox_status
                CHECK (status IN ('pending', 'inflight', 'dead_letter'))
        )
        """
    )
    op.execute("CREATE INDEX ix_care_outbox_poll ON care.care_outbox (status, next_attempt_at)")

    # ------------------------------------------------------------------
    # consumed_events - idempotent subscriber ledger (ADR-0002)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE care.consumed_events (
            event_id UUID PRIMARY KEY,
            event_type VARCHAR(100) NOT NULL,
            processed_at TIMESTAMPTZ NOT NULL,
            handler_result JSON
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS care.consumed_events")
    op.execute("DROP TABLE IF EXISTS care.care_outbox")
    op.execute("DROP TABLE IF EXISTS care.care_doctor_inputs")
    op.execute("DROP TABLE IF EXISTS care.care_rx_approvals")
    op.execute("DROP TABLE IF EXISTS care.care_rx_items")
    op.execute("DROP TABLE IF EXISTS care.care_prescriptions")
    op.execute("DROP TABLE IF EXISTS care.care_cases")
    op.execute("DROP SCHEMA IF EXISTS care CASCADE")
