"""v7.0__init_intake - MOD-005 intake schema storage foundation

PHASE-7 T01 (#345): the storage layer the symptom intake and AI
orchestration module builds on. Creates the ``intake`` schema with
``intake_intakes`` (mode, language, status, record attempts, text,
transcript, transcript-usability, forced-text, timestamps),
``intake_pre_summaries`` (structured fields JSONB, confidence,
low-confidence, review state, patient edits, doctor corrections, review
attribution + timestamp), ``intake_ai_jobs`` (task type, provider, model,
tokens, cost paise, status, error, confidence, duration, attempts),
``intake_media_refs`` (audio duration, size, record attempt), and the
module's transactional outbox + consumed-events ledger. All tables live
under the private ``intake`` schema with no cross-schema foreign keys
(ADR-0003). Table names follow the namespace prefix rule (coding-standards
§2): every table starts with ``intake_``.

Revision ID: 6cb15f638bec
Revises: dfde54f96bb1
Create Date: 2026-09-08 12:00:00.000000
"""

from collections.abc import Sequence

from alembic import op

revision: str = "6cb15f638bec"
down_revision: str | Sequence[str] | None = "dfde54f96bb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS intake")

    # ------------------------------------------------------------------
    # intake_intakes - the core intake record (FEAT-006, FEAT-007)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE intake.intake_intakes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            patient_id BIGINT NOT NULL,
            mode VARCHAR(10) NOT NULL,
            language VARCHAR(5) NOT NULL,
            status VARCHAR(30) NOT NULL DEFAULT 'captured',
            record_attempts INT NOT NULL DEFAULT 0,
            text TEXT,
            transcript TEXT,
            transcript_usability VARCHAR(20),
            forced_text BOOLEAN NOT NULL DEFAULT false,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_intake_intakes_mode
                CHECK (mode IN ('voice', 'text')),
            CONSTRAINT ck_intake_intakes_language
                CHECK (language IN ('hi', 'en')),
            CONSTRAINT ck_intake_intakes_status
                CHECK (status IN (
                    'captured', 'structuring', 'ready_for_review',
                    're_record', 'failed'
                )),
            CONSTRAINT ck_intake_intakes_transcript_usability
                CHECK (transcript_usability IS NULL OR transcript_usability IN (
                    'usable', 'partial', 'unusable'
                ))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_intake_intakes_patient ON intake.intake_intakes (patient_id, created_at)"
    )

    # ------------------------------------------------------------------
    # intake_pre_summaries - structured clinical summary (FEAT-007)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE intake.intake_pre_summaries (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            intake_id BIGINT NOT NULL,
            structured_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
            structuring_confidence NUMERIC(5,4),
            low_confidence BOOLEAN NOT NULL DEFAULT false,
            review_state VARCHAR(20) NOT NULL DEFAULT 'draft',
            patient_edits JSONB,
            doctor_corrections JSONB,
            review_attribution VARCHAR(40),
            reviewed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_intake_pre_summaries_intake
                FOREIGN KEY (intake_id) REFERENCES intake.intake_intakes (id),
            CONSTRAINT ck_intake_pre_summaries_review_state
                CHECK (review_state IN (
                    'draft', 'review_required', 'reviewed', 'final'
                )),
            CONSTRAINT ck_intake_pre_summaries_review_attribution
                CHECK (review_attribution IS NULL OR review_attribution IN (
                    'patient', 'doctor', 'system'
                ))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_intake_pre_summaries_intake ON intake.intake_pre_summaries (intake_id)"
    )

    # ------------------------------------------------------------------
    # intake_ai_jobs - LLM orchestration tracking (EXT-002, NFR-001)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE intake.intake_ai_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            intake_id BIGINT NOT NULL,
            task_type VARCHAR(30) NOT NULL,
            provider VARCHAR(30) NOT NULL,
            model VARCHAR(50) NOT NULL,
            input_tokens INT,
            output_tokens INT,
            cost_paise INT,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            error_message TEXT,
            confidence NUMERIC(5,4),
            duration_ms INT,
            attempts INT NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_intake_ai_jobs_intake
                FOREIGN KEY (intake_id) REFERENCES intake.intake_intakes (id),
            CONSTRAINT ck_intake_ai_jobs_task_type
                CHECK (task_type IN (
                    'transcribe', 'structure', 'draft', 'summarize'
                )),
            CONSTRAINT ck_intake_ai_jobs_status
                CHECK (status IN (
                    'pending', 'running', 'completed', 'failed', 'timeout'
                ))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_intake_ai_jobs_intake ON intake.intake_ai_jobs (intake_id, task_type)"
    )

    # ------------------------------------------------------------------
    # intake_media_refs - audio/photo metadata (object storage refs)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE intake.intake_media_refs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            intake_id BIGINT NOT NULL,
            media_type VARCHAR(10) NOT NULL,
            object_key TEXT NOT NULL,
            audio_duration_ms INT,
            file_size_bytes BIGINT,
            record_attempt INT NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_intake_media_refs_intake
                FOREIGN KEY (intake_id) REFERENCES intake.intake_intakes (id),
            CONSTRAINT ck_intake_media_refs_media_type
                CHECK (media_type IN ('audio', 'photo'))
        )
        """
    )
    op.execute("CREATE INDEX ix_intake_media_refs_intake ON intake.intake_media_refs (intake_id)")

    # ------------------------------------------------------------------
    # intake_outbox - transactional outbox (ADR-0002)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE intake.intake_outbox (
            id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
            event_id UUID NOT NULL,
            event_type VARCHAR(100) NOT NULL,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            occurred_at TIMESTAMPTZ NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            attempts INT NOT NULL DEFAULT 0,
            next_attempt_at TIMESTAMPTZ,
            CONSTRAINT ck_intake_outbox_status
                CHECK (status IN ('pending', 'inflight', 'dead_letter'))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_intake_outbox_poll ON intake.intake_outbox (status, next_attempt_at)"
    )

    # ------------------------------------------------------------------
    # consumed_events - idempotent subscriber ledger (ADR-0002)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE intake.consumed_events (
            event_id UUID PRIMARY KEY,
            event_type VARCHAR(100) NOT NULL,
            processed_at TIMESTAMPTZ NOT NULL,
            handler_result JSON
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS intake.consumed_events")
    op.execute("DROP TABLE IF EXISTS intake.intake_outbox")
    op.execute("DROP TABLE IF EXISTS intake.intake_media_refs")
    op.execute("DROP TABLE IF EXISTS intake.intake_ai_jobs")
    op.execute("DROP TABLE IF EXISTS intake.intake_pre_summaries")
    op.execute("DROP TABLE IF EXISTS intake.intake_intakes")
    op.execute("DROP SCHEMA IF EXISTS intake CASCADE")
