"""v2.1__init_consent - create the consent-schema lifecycle core

PHASE-3 T3 (#212): the MOD-004 data foundation, the consent half of the
spec's literal ``v2.0__init_health_consent.sql`` (the health half landed
with #211's revision). ``consent_consents`` - one row per grant lineage,
whose unique ``(patient_id, counterparty_type, counterparty_id,
record_scope)`` key IS the lineage identity and carries status + version -
plus ``consent_events``, the immutable lifecycle ledger (append-only:
versions never rewrite once terminal), and ``consent.consent_outbox``
mirroring the shared ``bus/outbox_ddl.py`` template. No subscriber ledger
yet: MOD-004's first subscription arrives with a later ticket. All tables
live in the private ``consent`` schema with no cross-schema foreign keys
(ADR-0003); the migration-immutability rule (ADR-0003 Consequences) keeps
this DDL frozen - it never imports current source.

Revision ID: 7be3a5c92d10
Revises: 9f2c41bae708
Create Date: 2026-08-24

"""

from collections.abc import Sequence

from alembic import op

revision: str = "7be3a5c92d10"
down_revision: str | Sequence[str] | None = "9f2c41bae708"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE consent.consent_consents (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            patient_id BIGINT NOT NULL,
            counterparty_type VARCHAR(20) NOT NULL,
            counterparty_id TEXT NOT NULL,
            record_scope VARCHAR(30) NOT NULL,
            status VARCHAR(20) NOT NULL,
            version BIGINT NOT NULL DEFAULT 0,
            -- C-YYYY-NNN minted at insert from the row id; briefly NULL inside
            -- the creating transaction (NULLs never collide in a unique index).
            lineage_ref VARCHAR(24),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_consent_consents_counterparty_type
                CHECK (counterparty_type IN ('doctor', 'lab', 'chemist')),
            CONSTRAINT ck_consent_consents_record_scope
                CHECK (record_scope IN (
                    'consultations', 'prescriptions', 'lab_results',
                    'metrics', 'full_record'
                )),
            CONSTRAINT ck_consent_consents_status
                CHECK (status IN ('requested', 'granted', 'revoked', 'declined')),
            CONSTRAINT ck_consent_consents_version CHECK (version >= 0),
            CONSTRAINT uq_consent_consents_lineage
                UNIQUE (patient_id, counterparty_type, counterparty_id, record_scope),
            CONSTRAINT uq_consent_consents_lineage_ref UNIQUE (lineage_ref)
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_consent_consents_patient_log "
        "ON consent.consent_consents (patient_id, updated_at DESC)"
    )
    op.execute(
        """
        CREATE TABLE consent.consent_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            consent_id BIGINT NOT NULL,
            kind VARCHAR(20) NOT NULL,
            version BIGINT NOT NULL DEFAULT 0,
            actor_patient_id BIGINT NOT NULL,
            occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_consent_events_consent
                FOREIGN KEY (consent_id) REFERENCES consent.consent_consents (id),
            CONSTRAINT ck_consent_events_kind
                CHECK (kind IN ('requested', 'granted', 'revoked', 'declined'))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_consent_events_lineage "
        "ON consent.consent_events (consent_id, occurred_at DESC, id DESC)"
    )
    op.execute(
        """
        CREATE TABLE consent.consent_outbox (
            id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
            event_id UUID NOT NULL,
            event_type VARCHAR(100) NOT NULL,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            occurred_at TIMESTAMPTZ NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            attempts INT NOT NULL DEFAULT 0,
            next_attempt_at TIMESTAMPTZ,
            CONSTRAINT ck_consent_outbox_status
                CHECK (status IN ('pending', 'inflight', 'dead_letter'))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_consent_outbox_poll ON consent.consent_outbox (status, next_attempt_at)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_consent_outbox_poll")
    op.execute("DROP TABLE IF EXISTS consent.consent_outbox")
    op.execute("DROP INDEX IF EXISTS ix_consent_events_lineage")
    op.execute("DROP TABLE IF EXISTS consent.consent_events")
    op.execute("DROP INDEX IF EXISTS ix_consent_consents_patient_log")
    op.execute("DROP TABLE IF EXISTS consent.consent_consents")
