"""v1.0__init_iam - create the five ``iam`` schema tables

PHASE-2 T1 (#52): the MOD-001 data foundation. ``identities``,
``otp_challenges``, ``sessions``, ``role_grants`` and the module's
transactional-outbox table all live in the private ``iam`` schema (ADR-0003).
``phone_e164`` is the unique duplicate-arbiter column (FEAT-001 Rule 1) and
identity status follows the canonical Unverified/Active/Suspended strings. The
``iam_outbox`` DDL mirrors the shared ``bus/outbox_ddl.py`` template but is
frozen here by the migration-immutability rule (ADR-0003 Consequences) - a
migration never imports current source.

Revision ID: 817e4c49f32c
Revises: dc0eaa6366a1
Create Date: 2026-08-12 23:33:29.890355

"""

from collections.abc import Sequence

from alembic import op

revision: str = "817e4c49f32c"
down_revision: str | Sequence[str] | None = "dc0eaa6366a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE iam.iam_identities (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            phone_e164 VARCHAR(32) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'Unverified',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_iam_identities_phone_e164 UNIQUE (phone_e164),
            CONSTRAINT ck_iam_identities_status
                CHECK (status IN ('Unverified', 'Active', 'Suspended'))
        )
        """
    )
    op.execute(
        """
        CREATE TABLE iam.iam_otp_challenges (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identity_id BIGINT NOT NULL,
            otp_hash VARCHAR(128) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'Pending',
            attempts INT NOT NULL DEFAULT 0,
            expires_at TIMESTAMPTZ NOT NULL,
            cooldown_until TIMESTAMPTZ,
            verified_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_iam_otp_challenges_identity
                FOREIGN KEY (identity_id) REFERENCES iam.iam_identities (id),
            CONSTRAINT ck_iam_otp_challenges_status
                CHECK (status IN ('Pending', 'Verified', 'Expired', 'Failed'))
        )
        """
    )
    op.execute(
        """
        CREATE TABLE iam.iam_sessions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            jti VARCHAR(64) NOT NULL,
            identity_id BIGINT NOT NULL,
            scope VARCHAR(255) NOT NULL,
            issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at TIMESTAMPTZ NOT NULL,
            revoked_at TIMESTAMPTZ,
            CONSTRAINT uq_iam_sessions_jti UNIQUE (jti),
            CONSTRAINT fk_iam_sessions_identity
                FOREIGN KEY (identity_id) REFERENCES iam.iam_identities (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE iam.iam_role_grants (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identity_id BIGINT NOT NULL,
            role VARCHAR(20) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'Active',
            granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            revoked_at TIMESTAMPTZ,
            CONSTRAINT fk_iam_role_grants_identity
                FOREIGN KEY (identity_id) REFERENCES iam.iam_identities (id),
            CONSTRAINT ck_iam_role_grants_role
                CHECK (role IN ('patient', 'partner', 'operator')),
            CONSTRAINT ck_iam_role_grants_status
                CHECK (status IN ('Active', 'Suspended'))
        )
        """
    )
    op.execute(
        """
        CREATE TABLE iam.iam_outbox (
            id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
            event_id UUID NOT NULL,
            event_type VARCHAR(100) NOT NULL,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            occurred_at TIMESTAMPTZ NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            attempts INT NOT NULL DEFAULT 0,
            next_attempt_at TIMESTAMPTZ,
            CONSTRAINT ck_iam_outbox_status
                CHECK (status IN ('pending', 'inflight', 'dead_letter'))
        )
        """
    )
    op.execute("CREATE INDEX ix_iam_outbox_poll ON iam.iam_outbox (status, next_attempt_at)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS iam.iam_outbox")
    op.execute("DROP TABLE IF EXISTS iam.iam_role_grants")
    op.execute("DROP TABLE IF EXISTS iam.iam_sessions")
    op.execute("DROP TABLE IF EXISTS iam.iam_otp_challenges")
    op.execute("DROP TABLE IF EXISTS iam.iam_identities")
