"""v4.0__init_partner - MOD-002 partner schema storage foundation

PHASE-5 T1 (#244): the storage layer the partner onboarding & gated
activation flow builds on. Expands the ``partner`` schema (a scaffold
holding only ``partner_identities`` today) with ``partner_service_areas``,
``partner_profiles`` (type + lifecycle status + mandatory geo),
``partner_credentials`` (type, verified flag, expiry, encrypted artifact
refs), ``partner_verifications`` (the operator queue, per-round decision
state) and the module's transactional outbox. The outbox DDL mirrors the
shared ``bus/outbox_ddl.py`` template but is frozen here by the
migration-immutability rule (ADR-0003 Consequences) - a migration never
imports current source.

Revision ID: 9d3a81dfcfa0
Revises: 1c8a3f72e905
Create Date: 2026-08-31 16:49:57.387673
"""

from collections.abc import Sequence

from alembic import op

revision: str = "9d3a81dfcfa0"
down_revision: str | Sequence[str] | None = "1c8a3f72e905"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS partner")

    op.execute(
        """
        CREATE TABLE partner.partner_service_areas (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(80) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_partner_service_areas_name UNIQUE (name)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE partner.partner_profiles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identity_id BIGINT NOT NULL,
            partner_type VARCHAR(20) NOT NULL,
            status VARCHAR(30) NOT NULL DEFAULT 'Registered',
            practice_name VARCHAR(120),
            practice_address TEXT NOT NULL,
            practice_latitude NUMERIC(9,6) NOT NULL,
            practice_longitude NUMERIC(9,6) NOT NULL,
            service_area_id BIGINT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_partner_profiles_identity UNIQUE (identity_id),
            CONSTRAINT ck_partner_profiles_partner_type
                CHECK (partner_type IN ('doctor', 'lab', 'chemist')),
            CONSTRAINT ck_partner_profiles_status
                CHECK (status IN (
                    'Registered', 'Under Verification', 'Active', 'Rejected'
                )),
            CONSTRAINT ck_partner_profiles_longitude
                CHECK (practice_longitude BETWEEN -180 AND 180),
            CONSTRAINT ck_partner_profiles_latitude
                CHECK (practice_latitude BETWEEN -90 AND 90)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE partner.partner_credentials (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            profile_id BIGINT NOT NULL,
            credential_type VARCHAR(40) NOT NULL,
            verified BOOLEAN NOT NULL DEFAULT false,
            expires_at TIMESTAMPTZ,
            artifact_refs JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_partner_credentials_profile
                FOREIGN KEY (profile_id) REFERENCES partner.partner_profiles (id),
            CONSTRAINT ck_partner_credentials_credential_type
                CHECK (credential_type IN (
                    'medical_registration', 'qualification_certificate',
                    'lab_license', 'accreditation',
                    'drug_license', 'pharmacist_registration'
                ))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_partner_credentials_profile ON partner.partner_credentials (profile_id)"
    )

    op.execute(
        """
        CREATE TABLE partner.partner_verifications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            profile_id BIGINT NOT NULL,
            round BIGINT NOT NULL DEFAULT 1,
            status VARCHAR(20) NOT NULL DEFAULT 'queued',
            decision VARCHAR(20),
            decision_reason TEXT,
            decision_by BIGINT,
            verification_started_at TIMESTAMPTZ,
            decided_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_partner_verifications_profile
                FOREIGN KEY (profile_id) REFERENCES partner.partner_profiles (id),
            CONSTRAINT ck_partner_verifications_status
                CHECK (status IN ('queued', 'in_review', 'approved', 'rejected')),
            CONSTRAINT ck_partner_verifications_decision
                CHECK (decision IN ('approved', 'rejected'))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_partner_verifications_queue "
        "ON partner.partner_verifications (status, created_at)"
    )
    op.execute(
        "CREATE INDEX ix_partner_verifications_profile "
        "ON partner.partner_verifications (profile_id, round)"
    )

    op.execute(
        """
        CREATE TABLE partner.partner_outbox (
            id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
            event_id UUID NOT NULL,
            event_type VARCHAR(100) NOT NULL,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            occurred_at TIMESTAMPTZ NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            attempts INT NOT NULL DEFAULT 0,
            next_attempt_at TIMESTAMPTZ,
            CONSTRAINT ck_partner_outbox_status
                CHECK (status IN ('pending', 'inflight', 'dead_letter'))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_partner_outbox_poll ON partner.partner_outbox (status, next_attempt_at)"
    )

    op.execute(
        """
        CREATE TABLE partner.consumed_events (
            event_id UUID PRIMARY KEY,
            event_type VARCHAR(100) NOT NULL,
            processed_at TIMESTAMPTZ NOT NULL,
            handler_result JSON
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS partner.consumed_events")
    op.execute("DROP TABLE IF EXISTS partner.partner_outbox")
    op.execute("DROP TABLE IF EXISTS partner.partner_verifications")
    op.execute("DROP TABLE IF EXISTS partner.partner_credentials")
    op.execute("DROP TABLE IF EXISTS partner.partner_profiles")
    op.execute("DROP TABLE IF EXISTS partner.partner_service_areas")
    op.execute("DROP SCHEMA IF EXISTS partner CASCADE")
