"""v2.0__init_health - create the health-schema record core

PHASE-3 T2 (#211): the MOD-003 data foundation. ``health_patient_records``
(one longitudinal shell per patient identity - the unique ``identity_id``
index is the idempotency arbiter for shell creation), ``health_record_entries``
(clinical entries attached from other modules via events in later phases) and
``health_record_access_history`` (the ledger that records EVERY read attempt,
owner reads included, feeding FEAT-003's trust view) all live in the private
``health`` schema (ADR-0003). The module's first real bus subscription
(``patient.registered`` -> shell creation) also needs its subscriber side:
``health.health_outbox`` mirrors the shared ``bus/outbox_ddl.py`` template and
``health.consumed_events`` is the idempotent-subscriber ledger; both are frozen
here by the migration-immutability rule (ADR-0003 Consequences) - a migration
never imports current source. The consent half of the spec's literal
``v2.0__init_health_consent.sql`` lands with T3's own revision.

Revision ID: 9f2c41bae708
Revises: bff3fd95f3db
Create Date: 2026-08-24

"""

from collections.abc import Sequence

from alembic import op

revision: str = "9f2c41bae708"
down_revision: str | Sequence[str] | None = "bff3fd95f3db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE health.health_patient_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identity_id BIGINT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_health_patient_records_identity UNIQUE (identity_id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE health.health_record_entries (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            record_id BIGINT NOT NULL,
            entry_type VARCHAR(40) NOT NULL,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            occurred_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_health_record_entries_record
                FOREIGN KEY (record_id) REFERENCES health.health_patient_records (id),
            CONSTRAINT ck_health_record_entries_entry_type
                CHECK (entry_type IN (
                    'consultation', 'prescription', 'lab_report', 'metric', 'settlement'
                ))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_health_record_entries_timeline "
        "ON health.health_record_entries (record_id, occurred_at DESC)"
    )
    op.execute(
        """
        CREATE TABLE health.health_record_access_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            record_id BIGINT NOT NULL,
            accessor_identity_id BIGINT NOT NULL,
            outcome VARCHAR(20) NOT NULL,
            accessed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_health_record_access_history_record
                FOREIGN KEY (record_id) REFERENCES health.health_patient_records (id),
            CONSTRAINT ck_health_record_access_history_outcome
                CHECK (outcome IN ('allowed', 'denied'))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_health_record_access_history_record "
        "ON health.health_record_access_history (record_id, accessed_at DESC)"
    )
    op.execute(
        """
        CREATE TABLE health.health_outbox (
            id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
            event_id UUID NOT NULL,
            event_type VARCHAR(100) NOT NULL,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            occurred_at TIMESTAMPTZ NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            attempts INT NOT NULL DEFAULT 0,
            next_attempt_at TIMESTAMPTZ,
            CONSTRAINT ck_health_outbox_status
                CHECK (status IN ('pending', 'inflight', 'dead_letter'))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_health_outbox_poll ON health.health_outbox (status, next_attempt_at)"
    )
    op.execute(
        """
        CREATE TABLE health.consumed_events (
            event_id UUID NOT NULL PRIMARY KEY,
            event_type VARCHAR(100) NOT NULL,
            processed_at TIMESTAMPTZ NOT NULL,
            handler_result JSONB
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS health.consumed_events")
    op.execute("DROP INDEX IF EXISTS ix_health_outbox_poll")
    op.execute("DROP TABLE IF EXISTS health.health_outbox")
    op.execute("DROP INDEX IF EXISTS ix_health_record_access_history_record")
    op.execute("DROP TABLE IF EXISTS health.health_record_access_history")
    op.execute("DROP INDEX IF EXISTS ix_health_record_entries_timeline")
    op.execute("DROP TABLE IF EXISTS health.health_record_entries")
    op.execute("DROP TABLE IF EXISTS health.health_patient_records")
