"""v8.8__iam_patient_profiles - patient profile-completion data (FEAT-008, #482)

PHASE-8.1 T1 (#482): ``iam.iam_patient_profiles`` persists the patient's
profile-completion data server-side so a returning patient is asked only once
and never re-enters details on a fresh device/login. One row per identity - the
unique ``identity_id`` is the upsert arbiter (``ON CONFLICT (identity_id) DO
UPDATE`` in the identity facade) - holding name/age/gender/preferred_language
plus the optional, unsettable area / emergency-contact / photo ref. The FK to
``iam_identities`` stays inside the ``iam`` schema (ADR-0003: no
cross-schema foreign keys).

Revision ID: ac4f18be6d92
Revises: 0f205ff8f67d
Create Date: 2026-09-19
"""

from collections.abc import Sequence

from alembic import op

revision: str = "ac4f18be6d92"
down_revision: str | Sequence[str] | None = "0f205ff8f67d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE iam.iam_patient_profiles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identity_id BIGINT NOT NULL,
            name VARCHAR(200) NOT NULL,
            age INT NOT NULL,
            gender VARCHAR(20) NOT NULL,
            preferred_language VARCHAR(20) NOT NULL,
            area VARCHAR(255),
            emergency_contact VARCHAR(32),
            photo_ref VARCHAR(255),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_iam_patient_profiles_identity UNIQUE (identity_id),
            CONSTRAINT fk_iam_patient_profiles_identity
                FOREIGN KEY (identity_id) REFERENCES iam.iam_identities (id)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE iam.iam_patient_profiles")
