"""v2.2__consent_egress_log - add the consent egress audit table

PHASE-3 FIX-2 (#221): ``consent.consent_egress_log`` is the append-only
audit ledger for every consent-mediated data egress event.  The SQLAlchemy
model already exists in ``consent/schema/models.py`` but the alembic
migration was never shipped, causing runtime failures on any egress-log
operation.  This migration creates the table with all constraints, indexes,
and server defaults matching the model definition exactly.

Revision ID: b27d495bfe70
Revises: 7be3a5c92d10
Create Date: 2026-08-25

"""

from collections.abc import Sequence

from alembic import op

revision: str = "b27d495bfe70"
down_revision: str | Sequence[str] | None = "7be3a5c92d10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE consent.consent_egress_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            patient_id BIGINT NOT NULL,
            consent_id BIGINT NOT NULL,
            lineage_ref VARCHAR(24) NOT NULL,
            version BIGINT NOT NULL,
            counterparty_type VARCHAR(20) NOT NULL,
            counterparty_id TEXT NOT NULL,
            record_scope VARCHAR(30) NOT NULL,
            disclosed_entry_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
            disclosed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_consent_egress_log_counterparty_type
                CHECK (counterparty_type IN ('doctor', 'lab', 'chemist')),
            CONSTRAINT ck_consent_egress_log_record_scope
                CHECK (record_scope IN (
                    'consultations', 'prescriptions', 'lab_results',
                    'metrics', 'full_record'
                ))
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_consent_egress_log_patient "
        "ON consent.consent_egress_log (patient_id, disclosed_at DESC)"
    )
    op.execute(
        "CREATE INDEX ix_consent_egress_log_consent "
        "ON consent.consent_egress_log (consent_id, disclosed_at DESC)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_consent_egress_log_consent")
    op.execute("DROP INDEX IF EXISTS ix_consent_egress_log_patient")
    op.execute("DROP TABLE IF EXISTS consent.consent_egress_log")
