"""v8.12__health_background_snapshot - patient-authored health background snapshot

#534 (US-21/US-22, ADR-0018): ``health.health_background_snapshots`` holds the
patient's own health background - blood group, conditions, allergies, current
medications, immunizations, family history - keyed to the patient identity
(one row per identity; the unique ``identity_id`` is the upsert arbiter). It is
patient-authored health-schema data, distinct from care-generated record
entries, and is surfaced to a doctor only later through a ``health_background``
consent check (never this surface). ``acknowledged_at`` is NULL until the first
acknowledged save, which records the standing ``health_background`` consent
grant; later edits never re-prompt.

Revision ID: d1c6f4a2b9e5
Revises: c3c52295eabf
Create Date: 2026-09-24
"""

from collections.abc import Sequence

from alembic import op

revision: str = "d1c6f4a2b9e5"
down_revision: str | Sequence[str] | None = "c3c52295eabf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE health.health_background_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identity_id BIGINT NOT NULL,
            acknowledged_at TIMESTAMPTZ,
            blood_group VARCHAR(16),
            conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
            allergies JSONB NOT NULL DEFAULT '[]'::jsonb,
            medications JSONB NOT NULL DEFAULT '[]'::jsonb,
            immunizations JSONB NOT NULL DEFAULT '[]'::jsonb,
            family_history JSONB NOT NULL DEFAULT '[]'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_health_background_snapshots_identity UNIQUE (identity_id)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE health.health_background_snapshots")
