"""v8.13__health_background_metrics - height/weight time series

#535 (US-23): ``health.health_background_metrics`` holds the timestamped
height/weight rows the patient appends alongside their health-background
snapshot, keyed to the patient identity (like ``health_background_snapshots``,
never cross-schema FK). Append-only in v1: rows are never updated or deleted on
this surface. ``recorded_at`` is the patient-authored measurement timestamp (the
trend anchor); the series read orders newest-first on ``(recorded_at, id)`` so a
future trend view pages without surprises. The plausible-range CHECKs mirror the
API boundary validation (height 30-250 cm, weight 1-500 kg) so a non-API writer
cannot store an absurd value, and the has-value check keeps an empty row out.

Revision ID: d3a7c1e90562
Revises: d1c6f4a2b9e5
Create Date: 2026-09-24
"""

from collections.abc import Sequence

from alembic import op

revision: str = "d3a7c1e90562"
down_revision: str | Sequence[str] | None = "d1c6f4a2b9e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE health.health_background_metrics (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identity_id BIGINT NOT NULL,
            height_cm NUMERIC(5,1),
            weight_kg NUMERIC(5,2),
            recorded_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_health_background_metrics_has_value
                CHECK (height_cm IS NOT NULL OR weight_kg IS NOT NULL),
            CONSTRAINT ck_health_background_metrics_height_cm
                CHECK (height_cm IS NULL OR (height_cm >= 30 AND height_cm <= 250)),
            CONSTRAINT ck_health_background_metrics_weight_kg
                CHECK (weight_kg IS NULL OR (weight_kg >= 1 AND weight_kg <= 500))
        )
        """
    )
    # One statement per op.execute: asyncpg refuses a multi-statement string
    # ("cannot insert multiple commands into a prepared statement").
    op.execute(
        """
        CREATE INDEX ix_health_background_metrics_series
            ON health.health_background_metrics (identity_id, recorded_at DESC, id DESC)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE health.health_background_metrics")
