"""v4.1__iam_roles_mfa - add operator MFA enrollment to the iam schema

PHASE-5 T1 (#244): operators are a trusted, closed group who hold the
activation gate (FEAT-015); MFA is required for operator login (user story
15). This migration adds the ``iam.iam_operator_mfa`` table - one row per
operator identity carrying the encrypted TOTP secret and verification
state. The ``partner`` / ``operator`` role values already exist on
``iam_role_grants`` (``ck_iam_role_grants_role`` includes 'partner' and
'operator'), so no role-grant DDL change is needed - this is MFA storage
only.

Revision ID: ec072bada6d3
Revises: 9d3a81dfcfa0
Create Date: 2026-08-31 16:49:58.889384
"""

from collections.abc import Sequence

from alembic import op

revision: str = "ec072bada6d3"
down_revision: str | Sequence[str] | None = "9d3a81dfcfa0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE iam.iam_operator_mfa (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identity_id BIGINT NOT NULL,
            secret VARCHAR(256) NOT NULL,
            mfa_enabled BOOLEAN NOT NULL DEFAULT false,
            enrolled_at TIMESTAMPTZ,
            last_verified_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_iam_operator_mfa_identity UNIQUE (identity_id),
            CONSTRAINT fk_iam_operator_mfa_identity
                FOREIGN KEY (identity_id) REFERENCES iam.iam_identities (id)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS iam.iam_operator_mfa")
