// FEAT-002 #648 + #661: the consent transport guards against the backend's real wire shape.
//
// The doctor console contract suite (#624) proved the pattern: page suites mock
// `@/lib/consent/api` wholesale, so the runtime guards inside the module never
// execute anywhere in CI and DTO drift is invisible until a patient opens the
// consent log. This suite drives the consent reads with the network stubbed and
// the module under test real, so the guards actually run - including the
// display-name field the correction added to `ConsentView` and `EgressLogEntry`.
//
// The fixtures are not hand-copied. Both DTOs live in the exported OpenAPI slice
// (openapi-doctor-console.json, regenerated by scripts/export_openapi_schemas.py
// and pinned by tests/unit/test_doctor_openapi_slice.py), so a backend rename
// fails here instead of failing a page. One generated removal case per declared
// field, so a field added to either DTO gets a guard without anyone remembering
// to add one - the same mechanism as the doctor cases suite.

import { beforeEach, describe, expect, it, vi } from "vitest";

import { fetchConsentLog, fetchEgressLog } from "./api";
import { request } from "@/lib/request";
import { makeSliceBody, type OpenApiNode } from "@/lib/openapiSliceBody";
import doctorConsoleSchema from "@/lib/doctor/openapi-doctor-console.json";

// The network layer is stubbed; the transport module under test is NOT.
vi.mock("@/lib/request", async (importOriginal) => {
  const mod = await importOriginal<typeof import("@/lib/request")>();
  return { ...mod, request: vi.fn() };
});

const ask = vi.mocked(request);

const schemas = (
  doctorConsoleSchema as unknown as { schemas: Record<string, OpenApiNode> }
).schemas;

const body = makeSliceBody(schemas);

/** One consent row exactly as the backend serialises it, clean and named. */
function consentRow(
  over: Record<string, unknown> = {},
): Record<string, unknown> {
  return body("ConsentView", {
    consent_id: 42,
    counterparty_type: "doctor",
    counterparty_id: "dv_77",
    counterparty_display_name: "Dr A Kumar",
    record_scope: "consultations",
    status: "granted",
    ...over,
  });
}

/** One consent-log body holding one row, or however many the case needs. */
function logBody(
  rows: Array<Record<string, unknown>> = [consentRow()],
): unknown {
  // ConsentLog itself is a one-key wrapper the slice does not carry; the DTOs
  // the correction added to the slice are what this suite walks.
  return { items: rows };
}

/** One egress row exactly as the backend serialises it, clean and named. */
function egressRow(
  over: Record<string, unknown> = {},
): Record<string, unknown> {
  return body("EgressLogEntry", {
    egress_id: 9,
    consent_id: 42,
    counterparty_type: "doctor",
    counterparty_id: "dv_77",
    counterparty_display_name: "Dr A Kumar",
    record_scope: "consultations",
    disclosed_entry_ids: [10, 11],
    ...over,
  });
}

/** One egress-log body holding one row, or however many the case needs. */
function egressBody(
  rows: Array<Record<string, unknown>> = [egressRow()],
): unknown {
  return { items: rows };
}

/** Ask a real read path to refuse a body, and report whether it did. */
async function refuses(
  shape: unknown,
  read: () => Promise<unknown>,
  guardMessage: string,
): Promise<boolean> {
  ask.mockResolvedValue(shape);
  try {
    await read();
    return false;
  } catch (error) {
    expect(String(error)).toContain(guardMessage);
    return true;
  }
}

const logRefuses = (shape: unknown) =>
  refuses(shape, () => fetchConsentLog(), "unexpected consent log shape");

const egressRefuses = (shape: unknown) =>
  refuses(shape, () => fetchEgressLog(), "unexpected egress log shape");

beforeEach(() => {
  ask.mockReset();
});

describe("the consent log against the served OpenAPI schema (#648)", () => {
  it("accepts a log the backend serves and hands the display name back", async () => {
    ask.mockResolvedValue(logBody());

    const log = await fetchConsentLog();

    expect(log.items).toHaveLength(1);
    expect(log.items[0].consent_id).toBe(42);
    expect(log.items[0].counterparty_display_name).toBe("Dr A Kumar");
  });

  it("accepts a null display name: an unresolved counterparty is not a malformed row", async () => {
    ask.mockResolvedValue(
      logBody([consentRow({ counterparty_display_name: null })]),
    );

    const log = await fetchConsentLog();

    expect(log.items[0].counterparty_display_name).toBeNull();
  });

  // One case per declared field, generated rather than written out: a field
  // added to ConsentView gets a removal case without anyone remembering to
  // add one.
  it.each(Object.keys(schemas.ConsentView.properties ?? {}))(
    "refuses a row missing %s",
    async (key) => {
      const row = consentRow();
      delete row[key];

      expect(await logRefuses(logBody([row]))).toBe(true);
    },
  );

  it("refuses a row whose display name is a number rather than a name or null", async () => {
    // The realistic drift: the enrichment arriving serialised, or as some
    // other value. It renders as a label, so the guard owns its shape rather
    // than the surface rendering `42` as who has access.
    expect(
      await logRefuses(
        logBody([consentRow({ counterparty_display_name: 42 })]),
      ),
    ).toBe(true);
    expect(
      await logRefuses(
        logBody([consentRow({ counterparty_display_name: { name: "Dr" } })]),
      ),
    ).toBe(true);
  });

  it("refuses a body that is not a consent log at all", async () => {
    expect(await logRefuses(null)).toBe(true);
    expect(await logRefuses("consents")).toBe(true);
    expect(await logRefuses({ total: 0 })).toBe(true);
    expect(await logRefuses({ items: {} })).toBe(true);
    expect(await logRefuses({ items: [null] })).toBe(true);
  });
});

describe("the egress log against the served OpenAPI schema (#648)", () => {
  it("accepts a log the backend serves and hands the display name back", async () => {
    ask.mockResolvedValue(egressBody());

    const log = await fetchEgressLog();

    expect(log.items).toHaveLength(1);
    expect(log.items[0].egress_id).toBe(9);
    expect(log.items[0].counterparty_display_name).toBe("Dr A Kumar");
  });

  it("accepts a null display name and a consent-less egress row", async () => {
    ask.mockResolvedValue(
      egressBody([
        egressRow({ counterparty_display_name: null, consent_id: null }),
      ]),
    );

    const log = await fetchEgressLog();

    expect(log.items[0].counterparty_display_name).toBeNull();
    expect(log.items[0].consent_id).toBeNull();
  });

  // One case per declared field, generated rather than written out: a field
  // added to EgressLogEntry gets a removal case without anyone remembering
  // to add one.
  it.each(Object.keys(schemas.EgressLogEntry.properties ?? {}))(
    "refuses a row missing %s",
    async (key) => {
      const row = egressRow();
      delete row[key];

      expect(await egressRefuses(egressBody([row]))).toBe(true);
    },
  );

  it("refuses a row whose display name is a number rather than a name or null", async () => {
    expect(
      await egressRefuses(
        egressBody([egressRow({ counterparty_display_name: 42 })]),
      ),
    ).toBe(true);
    expect(
      await egressRefuses(
        egressBody([egressRow({ counterparty_display_name: false })]),
      ),
    ).toBe(true);
  });

  it("refuses a body that is not an egress log at all", async () => {
    expect(await egressRefuses(null)).toBe(true);
    expect(await egressRefuses("egress")).toBe(true);
    expect(await egressRefuses({})).toBe(true);
    expect(await egressRefuses({ items: {} })).toBe(true);
    expect(await egressRefuses({ items: [null] })).toBe(true);
  });
});
